version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  app: