services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    develop:
      watch:
        # Sync all source code into the container except the .venv directory
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        # Rebuild if dependencies change
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

    # Command to start fastapi with reload
    command: ["/app/.venv/bin/fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "80"]

    # Prevent container from including your local .venv
    volumes:
      - /app/.venv